name: spendwise
description: "SpendSense: Smart expense tracking app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  characters: ^1.3.0
  speech_to_text: ^7.0.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  intl: ^0.19.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.0
  flutter_sms_inbox: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/puzzle.jpg
    - assets/pet_happy.gif
